build:
  stage: build
  image: maven:latest
  script:
    - mvn compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test


deploy:
  stage: deploy
  tags:
    - production
  script:
    - docker build --tag dbi .
    - docker run dbi
#   only:
#     - master
