build:
  stage: build
  image: maven:latest
  script:
    - mvn compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test


deploy:
  stage: deploy
  tags:
    - production
  script:
    - cp ~/config.properties ./
    - export running=$(docker service ls |grep dbi |awk '{print $1}')
    - if [ ! -z "$running" ]; then docker service rm $running; fi
    - docker build --tag dbi .
    - docker service create -p 42069:8500 --replicas 5 dbi
  only:
    - master
