build:
  stage: build
  image: maven:latest
  script:
    - mvn compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test


deploy:
  stage: deploy
  tags:
    - production
  script:
    - cp ~/config.properties ./
    - docker stop $(docker ps -a |grep dbi |awk '{print $1}')
    - docker rm $(docker ps -a |grep dbi |awk '{print $1}')
    - docker build --tag dbi .
    - docker run -d -p 42069:8500 dbi
  only:
    - master
