build:
  stage: build
  image: maven:latest
  script:
    - mvn compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test


deploy:
  stage: deploy
  script:
    - mvn clean
    - mvn install
    - ls
  tags:
    - production
#  only:
#    - master