build:
  stage: build
  image: maven:latest
  script:
    - mvn compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test


deploy:
  stage: deploy
  script:
    - export DBCONFIG="/home/usermcadmin/config.properties"
    - mvn clean
    - mvn install
    - sh session.sh
  tags:
    - production
#  only:
#    - master