build:
  stage: build
  image: maven:latest
  script:
    - mvn compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test


deploy:
  stage: deploy
  script:
    - export DB_CONFIG="/home/usermcadmin/config.properties"
    - mvn clean
    - mvn install
    - sh session.sh
#   only:
#     - master